#!/bin/bash

echo '<a href="https://leetcode.com/problems/<TASK>" target="_top"><TITLE> in <LANG> (External)</a>'
echo '<a href="https://www.hackerrank.com/challenges/<TASK>/problem" target="_top"><TITLE> in <LANG> (External)</a>'
