#!/bin/bash -e

if [[ $# -ne 1 ]]; then
    echo "Usage: $(basename $0) <all | <LANG> | NAME>"
    echo "Examples:"
    echo "$ $(basename $0) all"
    echo "$ $(basename $0) java"
    echo "$ $(basename $0) java/ArrayQueue.md"
    exit 1
fi

EXE_DIR=exercises
SRC_DIR=sources

function run() {
    local name=$1
    local exercise="$EXE_DIR/$name"
    local language
    local command
    if [[ ! -f $exercise ]]; then
        echo "$exercise not found"
        exit 1
    fi
    echo "Running $name..."
    language=$(sed -En 's/language:\s*(.*)/\1/p' $exercise)
    command=$(sed -En 's/command:\s*(.*)/\1/p' $exercise)
    pushd $SRC_DIR/$language/ >/dev/null
    bash -c "$command"
    popd >/dev/null
}

function run_all() {
    for path in $(find $EXE_DIR -name '*.md' | sort); do
        run ${path#*/}
    done
}

function run_lang() {
    lang=$1
    for path in $(find $EXE_DIR/$lang -name '*.md' | sort); do
        run ${path#*/}
    done
}

what=$1
case $what in
    "all") run_all;;
    "c" | "erlang" | "java" | "python") run_lang $what;;
    *) run $what
esac
