#!/bin/bash -e

DIR=$(dirname $0)
VER=70aaa22b3f9ad30c8566024bf25484fd1ed9bda9

if [[ ! -d $DIR/app/ ]]; then
   git clone https://github.com/Rob--W/cors-anywhere.git $DIR/app/
   cd $DIR/app/
else
   cd $DIR/app/
   git fetch origin
fi

git checkout $VER

npm install
cd ..

docker build --tag cors-anywhere .
